### ISSUE TITLE
tableExport does not work in safari (Mac)

### ISSUE THREAD

**Issue by vjdeeds** [hhurz/tableExport.jquery.plugin#109] opened 2016-09-08 09:48 UTC
When trying to download in any file format in Safari (Mac). I just get a bank new safari tab. Chrome it is working like a charm. Please suggest?

**Comment by hhurz** [comment] 2016-09-08 18:56
This is a duplicate of this issue https://github.com/hhurz/tableExport.jquery.plugin/issues/73
tableExport is using [FileSaver.js](https://github.com/eligrey/FileSaver.js) to save a file. Please look also on that plugins homepage for further information. 
Just tested it again: For me some file types (csv, txt, pdf,png) open in a new browser tab as blob:... Other file types (json, xls, doc) open a new empty browser tab and no file is downloaded.

**Closed as completed** 2016-10-03 18:59 UTC
Labels: duplicate
