### ISSUE TITLE
only exporting visible rows, not all the rows

### ISSUE THREAD

**Issue by durgasekar** [hhurz/tableExport.jquery.plugin#158] opened 2017-04-11 09:45 UTC

**Comment by bakiyuksel** [comment] 2017-04-11 11:51
disable pagination when exporting

**Comment by durgasekar** [comment] 2017-04-11 11:52
Thank you :)

**Comment by durgasekar** [comment] 2017-04-11 11:56
Is der any other way @SaluteMB

**Comment by hhurz** [comment] 2017-04-11 18:43
Duplicate of issue #153, #122, #85, #54, and #26

**Comment by bakiyuksel** [comment] 2017-04-12 14:47
I linked it to a new page that closes after download is done. On that page it loads all rows of the table. @durgasekar

**Closed as completed** 2017-04-20 14:48 UTC
Labels: duplicate
