### ISSUE TITLE
Wrong sql export

### ISSUE THREAD

**Issue by arivera12** [hhurz/tableExport.jquery.plugin#144] opened 2017-02-11 04:17 UTC
Test HTML

```
<table class="table">
    <thead>
        <tr>
            <th>class name</th>
            <th>class code</th>
            <th>class comments</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
            <td>3</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>class name</th>
            <th>class code</th>
            <th>class comments</th>
        </tr>
    </tfoot>
</table>
```

Output:

`INSERT INTO `myTableName` ('class name','class code','class comments') VALUES ('1','2','3'),('class name','class code','class comments');`

**Comment by hhurz** [comment] 2017-02-11 12:18
Duplicate of issue #142

**Closed as completed** 2017-02-11 20:10 UTC
Labels: duplicate
