### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by RZsam** [hhurz/tableExport.jquery.plugin#188] opened 2017-08-28 11:28 UTC
how to add utf-8 to tableExport? arabic alphabet are seprated in png

**Comment by hhurz** [comment] 2017-08-28 18:30
May be this is a duplicate of issue #159. If not, please provide more information of what you intend to do.

**Comment by RZsam** [comment] 2017-08-29 05:55
@hhurz yeah I've read that issue too .I want to know is anyway to support utf-8?
 somehow you managed to fix it in excel

**Comment by hhurz** [comment] 2017-08-30 19:11
In which format do you want to export to? In case of pdf, it is only possible with pdfmake as pdf producer. jsPDF is only able to export a few utf8 characters, but defenitely no arabic text.

**Comment by RZsam** [comment] 2017-08-31 06:22
@hhurz with pdfmake arabic text is possible?

**Comment by hhurz** [comment] 2017-08-31 09:26
I added a [pdfmake example for arabic text](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/arabicPdfmake.html) based on the code provided in issue #159.

**Closed as completed** 2017-09-02 05:20 UTC
Labels: example requierd
