### ISSUE TITLE
It does not export all the data in a paged table.

### ISSUE THREAD

**Issue by ShiruJan** [hhurz/tableExport.jquery.plugin#187] opened 2017-08-24 00:25 UTC
Hello, 

I am using the "Bootgrid" plugin to improve the appearance and functionality of the tables. When I export data in any format, it does not display all the data when the table is paged.

Attach example:

The table contains 11 records, the first page shows 10 records.
(Page 1)

![captura de pantalla 2017-08-23 a la s 19 17 44](https://user-images.githubusercontent.com/11635458/29643917-e1dbbd36-8837-11e7-92a8-859cb6b7d1e3.png)

(Page 2)

![captura de pantalla 2017-08-23 a la s 19 18 21](https://user-images.githubusercontent.com/11635458/29643936-042ff2d0-8838-11e7-9cd7-073c40fdb61c.png)

I export the table to xlsx and it only shows the records of the first page.

![captura de pantalla 2017-08-23 a la s 19 18 11](https://user-images.githubusercontent.com/11635458/29643948-1698120e-8838-11e7-8bd4-bfab91c1cdd9.png)

Is this an error or does it need some configuration?
Thank you.

**Comment by SRaiz** [comment] 2017-08-24 09:12
For exporting the data of other pages too. Create a new hidden table which is having all the data you want to export and then export that hidden table on export button click. By using the attribute as follows:-

Creation of table:-
_<table class="table table-striped" id="myHiddenTable" **style="display:none;" data-tableexport-display="always"** data-toolbar="#toolbar">
    
</table>_

Calling the function to export as excel:-
                           $('#mytableExportExcel').tableExport({
                                type:'excel',
                                fileName: 'ExportAll',
                                escape:false
                            });

**Comment by hhurz** [comment] 2017-08-24 13:38
This isssue is a duplicate of #182. 

This plugin requires that all table data is available on client side AND filled into a html table. If the html table only contains the data of the actually viewed page, then the plugin can not retrieve all data for you. Thus you have to find a way to retreive all data and put it into a (probably hidden) html table before you can export it. @SRaiz (Thank you) gave an example how you could do that.

**Closed as completed** 2017-09-21 09:03 UTC
Labels: duplicate, Q&A
